version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:                               
      - echo Build started on `date`
      - echo Building java
      - mvn clean package
      - echo Building the docker image
      - docker build -t authorization-service .
      - docker tag authorization-service 860061945305.dkr.ecr.ap-south-1.amazonaws.com/pms-authorization-service-ecr:Auth
  post_build:
    commands:
      - echo Build completed on `date`   
      - docker push 860061945305.dkr.ecr.ap-south-1.amazonaws.com/pms-authorization-service-ecr:Auth
      - echo Writing definition files
      - printf '[{"name":"pms-authorization-service-container","imageUri":"%s"}]' 860061945305.dkr.ecr.ap-south-1.amazonaws.com/pms-authorization-service-ecr:Auth > taskdefinition.json

artifacts:
  files: taskdefinition.json
